apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    type: demo-voting-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: result-app-pod
    type: demo-voting-app

